name: mac-spoofer
version: '0.1'
summary: force a different mac address for your network devices
description: |
  While usually MAC addresses are hardware bound, this daemon uses the ip
  tool to restart your network devices with a different, manually assigned
  hardware address instead of the one obtained by the hardware.

  Make sure to connect the network-control and network-observe snap
  interfaces for this tool to operate correctly.

grade: stable
confinement: strict
base: core20

apps:
  mac-spoofer:
    command: bin/mac-spoofer.sh
    daemon: simple
    plugs:
      - network
      - network-bind
      - network-control
      - network-observe

parts:
  mac-spoofer:
    plugin: dump
    source: .
    organize:
      mac-spoofer.sh: bin/mac-spoofer.sh
